module.exports = {
    '200': {httpStatusCode: 200, message: ''},
    '400': {httpStatusCode: 200, message: 'Bad Request'},
    '401': {httpStatusCode: 401, message: 'Unauthorized'},
    '402': {httpStatusCode: 402, message: 'Payment Required'},
    '403': {httpStatusCode: 403, message: 'Forbidden'},
    '404': {httpStatusCode: 404, message: 'Not Found'},
    '405': {httpStatusCode: 405, message: 'Method Not Allowed'},
    '406': {httpStatusCode: 406, message: 'Not Acceptable'},
    '407': {httpStatusCode: 407, message: 'Proxy Authentication Required'},
    '408': {httpStatusCode: 408, message: 'Request Time-out'},
    '409': {httpStatusCode: 409, message: 'Conflict'},
    '410': {httpStatusCode: 410, message: 'Gone'},
    '411': {httpStatusCode: 411, message: 'Length Required'},
    '412': {httpStatusCode: 412, message: 'Precondition Failed'},
    '413': {httpStatusCode: 413, message: 'Request Entity Too Large'},
    '414': {httpStatusCode: 414, message: 'Request-URI Too Large'},
    '415': {httpStatusCode: 415, message: 'Unsupported Media Type'},
    '416': {httpStatusCode: 416, message: 'Requested Range Not Satisfiable'},
    '417': {httpStatusCode: 417, message: 'Expectation Failed'},
    '418': {httpStatusCode: 418, message: "I'm a Teapot"},
    '422': {httpStatusCode: 422, message: 'Unprocessed Entity'},
    '423': {httpStatusCode: 423, message: 'Locked'},
    '428': {httpStatusCode: 428, message: 'Precondition Required'},
    '429': {httpStatusCode: 429, message: 'Too Many Requests'},
    '451': {httpStatusCode: 451, message: 'Unavailable For Legal Reasons'},
    '500': {httpStatusCode: 500, message: 'Internal Server Error'},
    '501': {httpStatusCode: 501, message: 'Not Implemented'},
    '502': {httpStatusCode: 502, message: 'Bad Gateway'},
    '503': {httpStatusCode: 503, message: 'Service Unavailable'},
    '504': {httpStatusCode: 504, message: 'Gateway Time-out'}
}